schema = "3"
[package]
name = "economoist"
version = "0.2.16"
compiler = "=0.19.1"
module_prefix = "Economoist"
additional_sources = ["properties", "demos", "sampled"]
resolver = "2"

[dependencies]
chelis-std = { version = "=0.4.0" }
