[package]
name = "economoist"
version = "0.2.14"
compiler = "=0.18.12"
module_prefix = "Economoist"
additional_sources = ["properties", "demos", "sampled"]

[dependencies]
chelis-std = { version = "0.4.0" }
